[tool.poetry]
name = "jarvis"
version = "0.1.0"
description = "Interactive CrewAI project for summarizing and testing from documents"
authors = ["Gopinath <gopinath.kumar@freightify.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
# Core CrewAI packages
crewai = "*"
crewai-tools = "*"
# File readers
python-docx = "*"
PyPDF2 = "*"
unstructured = "*"
pypdf = "*"
pandas = "*"
pytest = '*'

# Helpers
python-dotenv = "*"
tiktoken = "*"

# Vector DB and embedding
chromadb = "*"
openai = "*"
langchain = "*"
langchain-openai = '*'
langchain-chroma = '*'
langchain-community = '*'
langchain-ollama = "^0.3.4"
streamlit = "^1.46.1"

pysqlite3-binary = "*"
google-generativeai = "*"

[[tool.poetry.packages]]
include = "doc_analysis"
from = "src"